basePath: /v1
consumes:
- application/json
definitions:
  models.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.Land_Aboutus_Request:
    properties:
      aboutus_component_id:
        description: Primary key
        type: integer
      aboutus_component_jobdesc:
        type: string
      aboutus_component_name:
        type: string
      aboutus_component_photo:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      description:
        type: string
      status:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Aboutus_Response:
    properties:
      aboutus_component_id:
        type: integer
      aboutus_component_jobdesc:
        type: string
      aboutus_component_name:
        type: string
      aboutus_component_photo:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      description:
        type: string
      status:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Faq_Request:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      faq_category:
        type: integer
      faq_description:
        type: string
      faq_id:
        type: integer
      faq_title:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Faq_Response:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      faq_category:
        type: integer
      faq_description:
        type: string
      faq_id:
        type: integer
      faq_title:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Footer_Request:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      endpoint:
        type: string
      footer_component_group:
        description: Foreign key
        type: integer
      footer_component_icon:
        type: string
      footer_component_id:
        description: Primary key
        type: integer
      footer_component_name:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Footer_Response:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      endpoint:
        type: string
      footer_component_group:
        type: integer
      footer_component_icon:
        type: string
      footer_component_id:
        type: integer
      footer_component_name:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.Land_Hero_Response:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      hero_component_cover_img:
        type: string
      hero_component_id:
        type: integer
      hero_component_image:
        type: string
      hero_component_subtitle:
        type: string
      hero_component_title:
        type: string
      tooltip:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  models.SignUpRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  models.UpdatePasswordAfterForgotPassword:
    properties:
      new_password:
        type: string
    required:
    - new_password
    type: object
host: https://selfieapi.up.railway.app
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: RESTful Self-ie Academy API Services. Built to ensure Self-ie Services
    are good to be served!
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Self-Ie API Services
  version: "1.0"
paths:
  /aboutus:
    get:
      consumes:
      - application/json
      description: Get all About Us components
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Land_Aboutus_Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all About Us components
      tags:
      - AboutUs
    post:
      consumes:
      - application/json
      description: Create a new About Us component
      parameters:
      - description: About Us component data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Land_Aboutus_Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Land_Aboutus_Response'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create a new About Us component
      tags:
      - AboutUs
  /auth/failed:
    get:
      consumes:
      - application/json
      description: When Redirected To This Service, It Will Return JSON Response With
        Various Error Message
      parameters:
      - description: Get The type Value When Being Redirected from Forgot Password
          Recovery or Verify Signup
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Failed Auth Service Messages and Status Responser
      tags:
      - Auth Service
  /auth/send-forgot-password-email:
    post:
      consumes:
      - application/json
      description: Request Body need email.
      parameters:
      - description: Forgot Password Requirement
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Send Email For Forgot Password Feature
      tags:
      - Auth Service
  /auth/signin-email-password:
    post:
      consumes:
      - application/json
      description: Signing In A User Using Email and Password. Request Body need email
        and password.
      parameters:
      - description: Sign In Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Sign In A User With Email Password
      tags:
      - Auth Service
  /auth/signout:
    post:
      consumes:
      - application/json
      description: Signing Out A User. Required Authenticated User.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Sign Out A User
      tags:
      - Auth Service
  /auth/signup-admin:
    post:
      consumes:
      - application/json
      description: Signing Up A Admin Using Email and Password. Request Body need
        email, password, and username.
      parameters:
      - description: Sign Up Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Sign Up A Admin With Email Password
      tags:
      - Auth Service
  /auth/signup-email-password:
    post:
      consumes:
      - application/json
      description: Signing Up A User Using Email and Password. Request Body need email,
        password, and username.
      parameters:
      - description: Sign Up Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Sign Up A User With Email Password
      tags:
      - Auth Service
  /auth/signup-super:
    post:
      consumes:
      - application/json
      description: Signing Up A SuperUser Using Email and Password. Request Body need
        email, password, and username.
      parameters:
      - description: Sign Up Credentials
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.SignUpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Sign Up A SuperUser With Email Password
      tags:
      - Auth Service
  /auth/update-user-password:
    put:
      consumes:
      - application/json
      description: Request Body need new_password.
      parameters:
      - description: Update The Password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.UpdatePasswordAfterForgotPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Update The User Password (After Confirming From Verify Password Recovery)
      tags:
      - Auth Service
  /auth/verify-password-recovery:
    get:
      consumes:
      - application/json
      description: Request Body need email, password, and username. Required SendForgotPasswordEmail.
      parameters:
      - description: The Request Type From Confirmation Email
        in: query
        name: type
        required: true
        type: string
      - description: Secret Token Hashed From Confirmation Email
        in: query
        name: token_hash
        required: true
        type: string
      - description: Redirect API URL From Confirmation Email
        in: query
        name: redirect_to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Verifying Forgotten Password
      tags:
      - Auth Service
  /auth/verify-signup:
    get:
      consumes:
      - application/json
      description: Not Very Useful At The Moment
      parameters:
      - description: The Request Type From Confirmation Email
        in: query
        name: type
        required: true
        type: string
      - description: Secret Token Hashed From Confirmation Email
        in: query
        name: token_hash
        required: true
        type: string
      - description: Redirect API URL From Confirmation Email
        in: query
        name: redirect_to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Verify New Signed Up User
      tags:
      - Auth Service
  /faq:
    get:
      consumes:
      - application/json
      description: Get all FAQ components
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Land_Faq_Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all FAQ components
      tags:
      - FAQ
    post:
      consumes:
      - application/json
      description: Create a new FAQ component
      parameters:
      - description: FAQ component data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Land_Faq_Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Land_Faq_Response'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create a new FAQ component
      tags:
      - FAQ
  /faq/{id}:
    get:
      consumes:
      - application/json
      description: Get a FAQ component by ID
      parameters:
      - description: FAQ component ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Land_Faq_Response'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get a FAQ component by ID
      tags:
      - FAQ
    put:
      consumes:
      - application/json
      description: Update a FAQ component
      parameters:
      - description: FAQ component ID
        in: path
        name: id
        required: true
        type: integer
      - description: Updated FAQ component data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Land_Faq_Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Land_Faq_Response'
        "400":
          description: Bad Request
          schema:
            type: object
        "404":
          description: Not Found
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Update a FAQ component
      tags:
      - FAQ
  /footer:
    get:
      consumes:
      - application/json
      description: Get all Footer components
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Land_Footer_Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all Footer components
      tags:
      - Footer
    post:
      consumes:
      - application/json
      description: Create a new Footer component
      parameters:
      - description: Footer component data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Land_Footer_Request'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Land_Footer_Response'
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Create a new Footer component
      tags:
      - Footer
  /hero:
    get:
      consumes:
      - application/json
      description: Get all hero components
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Land_Hero_Response'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all hero components
      tags:
      - Hero
produces:
- application/json
swagger: "2.0"
